name: motiondreamer
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - torchvision
      - opencv-python-headless
      - roma
      - mesh2sdf
      - smplx
      - pymeshlab
      - numpy==1.*
      - diffusers==0.27.2
      - transformers==4.39.3
      - huggingface_hub==0.24.6
      - imageio==2.19.3
      - imageio-ffmpeg==0.4.7
      - open3d
      - iopath
      - tensorboard
      - trimesh 
      - libigl
      - pytorch_lightning==1.9.3
      - matplotlib 
      - easydict 
      - cholespy 
      - fire
      - omegaconf==2.1.1
      - einops
      - accelerate
      - kornia
      - open_clip==2.12.0
      - xformers
      - chumpy
